name: Test Secret

on:
  push:
    branches:
      - main

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Print Secret
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
        run: echo "CR_PAT secret value is $CR_PAT"
